name: Go+

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go+
      uses: goplus/setup-goplus@v1
      with:
        go-version: '1.20'
        gop-version: '1.1'

    - name: Build
      run: gop build -v ./...

    - name: Test
      run: gop test -v ./...

    - name: Run
      run: gop run .
